baseURL = "http://unimeta.site/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "普洋会计服务有限公司"
[[menu.main]]
name = "首页"
url = "#home"
weight = 1
[[menu.main]]
name = "普洋简介"
url = "#about"
weight = 2
[[menu.main]]
name = "服务列表"
url = "#service"
weight = 3
[[menu.main]]
name = "普洋动态"
url = "#blog"
weight = 7
[[menu.main]]
name = "联系我们"
url = "#contact"
weight = 8
[[menu.sitemap]]
name = "普洋简介"
url = "about"
weight = 1
[[menu.sitemap]]
name = "常见问题"
url = "#"
weight = 2
[[menu.sitemap]]
name = "普洋动态"
url = "#"
weight = 4
[params]
blogPageURL = "blog"
contactLink = "联系我们"
copyright = "秦皇岛普洋会计服务有限公司"
footerLogo = "/images/logo.png"
formspreeURL = ""
googleAnalytics = ""
logo = "/images/logo.png"
[params.address]
address = "河北省秦皇岛市海港区西港路金港花园东门金港房地产大厦五楼"
email = "27729911@qq.com"
openingHours = ""
phone = "13230316911"
[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
