baseURL = "http://unimeta.site/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "普洋会计服务有限公司"
[[menu.main]]
name = "首页"
url = "#home"
weight = 1
[[menu.main]]
name = "普洋简介"
url = "#about"
weight = 2
[[menu.main]]
name = "服务列表"
url = "#service"
weight = 3
[[menu.main]]
name = "普洋动态"
url = "#blog"
weight = 7
[[menu.main]]
name = "联系我们"
url = "#contact"
weight = 8
[[menu.sitemap]]
name = "普洋简介"
url = "about"
weight = 1
[[menu.sitemap]]
name = "常见问题"
url = "#"
weight = 2
[[menu.sitemap]]
name = "普洋动态"
url = "#"
weight = 4
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"
[params.address]
address = "23 Khan Niketon, Grand Street, NYK."
email = "hello@example.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(448) 833 5272 332"
[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
